from django.urls import path

from cards.views import (
    misc,
    notifications,
    cards,
    courses,
    profile
)

urlpatterns = [
    path(
        '',
        misc.Index.as_view(),
        name='index'
    ),
    path(
        'cards/',
        cards.Cards.as_view(),
        name='cards'
    ),
    path(
        'cards_add/',
        cards.CardAddView.as_view(),
        name='cards_add'
    ),
    path(
        'courses/',
        courses.Courses.as_view(),
        name='courses'
    ),
    path(
        'share/',
        courses.ShareView.as_view(),
        name='share'
    ),
    path(
        'notifications/',
        notifications.NotificationsView.as_view(),
        name='notifications'
    ),
    path(
        'notifications/read',
        notifications.NotificationReadView.as_view(),
        name='notification_read'
    ),
    path(
        'achievements/',
        profile.AchievementsView.as_view(),
        name='achievements'
    ),
    path(
        'profile/',
        profile.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'accounts/signup/',
        profile.SignUpView.as_view(),
        name='signup'
    ),
]
