# Generated by Django 3.2 on 2021-04-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_achievement_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.achievement')),
                ('level', models.IntegerField()),
            ],
            bases=('cards.achievement',),
        ),
        migrations.CreateModel(
            name='SiteAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.achievement')),
                ('path', models.CharField(max_length=100)),
            ],
            bases=('cards.achievement',),
        ),
    ]
