# Generated by Django 3.2 on 2021-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
